-- AI Assistant: lịch sử chat tối giản + quota server-side.
-- Chạy một lần trong Supabase SQL Editor.
-- Backend dùng service_role; không đưa khóa Supabase/Groq ra frontend.

CREATE TABLE IF NOT EXISTS public.ai_conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT 'Cuộc trò chuyện mới',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ai_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id uuid NOT NULL REFERENCES public.ai_conversations(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('user', 'assistant')),
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ai_daily_usage (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  usage_date date NOT NULL,
  used_count integer NOT NULL DEFAULT 0 CHECK (used_count >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, usage_date)
);

CREATE INDEX IF NOT EXISTS ai_conversations_user_updated_idx
  ON public.ai_conversations (user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS ai_messages_conversation_created_idx
  ON public.ai_messages (conversation_id, created_at ASC);
CREATE INDEX IF NOT EXISTS ai_daily_usage_date_idx
  ON public.ai_daily_usage (usage_date);

CREATE OR REPLACE FUNCTION public.ai_reserve_daily_quota(
  p_user_id uuid,
  p_usage_date date,
  p_limit integer DEFAULT 20
)
RETURNS TABLE (used_count integer, limit_count integer, allowed boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_count integer;
BEGIN
  SELECT used_count INTO current_count
  FROM public.ai_daily_usage
  WHERE user_id = p_user_id AND usage_date = p_usage_date
  FOR UPDATE;

  IF COALESCE(current_count, 0) >= p_limit THEN
    RETURN QUERY SELECT COALESCE(current_count, 0), p_limit, false;
    RETURN;
  END IF;

  INSERT INTO public.ai_daily_usage (user_id, usage_date, used_count, updated_at)
  VALUES (p_user_id, p_usage_date, 1, now())
  ON CONFLICT (user_id, usage_date) DO UPDATE
    SET used_count = public.ai_daily_usage.used_count + 1,
        updated_at = now()
  RETURNING ai_daily_usage.used_count INTO current_count;

  RETURN QUERY SELECT current_count, p_limit, true;
END;
$$;

CREATE OR REPLACE FUNCTION public.ai_release_daily_quota(
  p_user_id uuid,
  p_usage_date date
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.ai_daily_usage
  SET used_count = GREATEST(used_count - 1, 0), updated_at = now()
  WHERE user_id = p_user_id AND usage_date = p_usage_date;
$$;

CREATE OR REPLACE FUNCTION public.ai_get_daily_quota(
  p_user_id uuid,
  p_usage_date date,
  p_limit integer DEFAULT 20
)
RETURNS TABLE (used_count integer, limit_count integer)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT used_count FROM public.ai_daily_usage
     WHERE user_id = p_user_id AND usage_date = p_usage_date),
    0
  ), p_limit;
$$;

ALTER TABLE public.ai_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_daily_usage ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.ai_conversations, public.ai_messages, public.ai_daily_usage FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ai_reserve_daily_quota(uuid, date, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.ai_release_daily_quota(uuid, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.ai_get_daily_quota(uuid, date, integer) TO service_role;

DROP POLICY IF EXISTS ai_conversations_own_select ON public.ai_conversations;
DROP POLICY IF EXISTS ai_conversations_own_delete ON public.ai_conversations;
DROP POLICY IF EXISTS ai_messages_own_select ON public.ai_messages;
DROP POLICY IF EXISTS ai_daily_usage_own_select ON public.ai_daily_usage;

CREATE POLICY ai_conversations_own_select ON public.ai_conversations
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY ai_conversations_own_delete ON public.ai_conversations
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY ai_messages_own_select ON public.ai_messages
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.ai_conversations c
    WHERE c.id = conversation_id AND c.user_id = auth.uid()
  ));
CREATE POLICY ai_daily_usage_own_select ON public.ai_daily_usage
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
