-- Class Money / Tiền lớp
-- Backend-only authorization: requireAuth + requireMember + requireAdmin.
-- Chạy một lần trong Supabase SQL Editor. Không thay đổi bảng hiện có.

CREATE TABLE IF NOT EXISTS public.class_money_books (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL CHECK (char_length(trim(name)) BETWEEN 1 AND 120),
  description text NOT NULL DEFAULT '',
  currency text NOT NULL DEFAULT 'VND' CHECK (currency = 'VND'),
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.class_money_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id uuid NOT NULL REFERENCES public.class_money_books(id) ON DELETE CASCADE,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  display_name_snapshot text NOT NULL CHECK (char_length(trim(display_name_snapshot)) BETWEEN 1 AND 120),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (book_id, profile_id)
);

CREATE TABLE IF NOT EXISTS public.class_money_collections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id uuid NOT NULL REFERENCES public.class_money_books(id) ON DELETE CASCADE,
  name text NOT NULL CHECK (char_length(trim(name)) BETWEEN 1 AND 120),
  amount_per_person bigint NOT NULL CHECK (amount_per_person >= 0),
  due_date date,
  note text NOT NULL DEFAULT '',
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed', 'archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.class_money_collection_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  collection_id uuid NOT NULL REFERENCES public.class_money_collections(id) ON DELETE CASCADE,
  profile_id uuid REFERENCES public.profiles(id) ON DELETE RESTRICT,
  student_number integer CHECK (student_number IS NULL OR student_number > 0),
  display_name_snapshot text NOT NULL CHECK (char_length(trim(display_name_snapshot)) BETWEEN 1 AND 120),
  amount_due bigint NOT NULL CHECK (amount_due >= 0),
  amount_paid bigint NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
  amount_owed bigint NOT NULL DEFAULT 0 CHECK (amount_owed >= 0),
  amount_change bigint NOT NULL DEFAULT 0 CHECK (amount_change >= 0),
  status text NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'debt', 'paid', 'change')),
  note text NOT NULL DEFAULT '',
  photo_url text NOT NULL DEFAULT '',
  paid_at timestamptz,
  paid_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Chạy an toàn khi database đã có bảng từ phiên bản trước.
ALTER TABLE public.class_money_collection_members
  ADD COLUMN IF NOT EXISTS photo_url text NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS public.class_money_expenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id uuid NOT NULL REFERENCES public.class_money_books(id) ON DELETE CASCADE,
  title text NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 160),
  amount bigint NOT NULL CHECK (amount > 0),
  category text NOT NULL DEFAULT '',
  spent_at date NOT NULL DEFAULT CURRENT_DATE,
  spent_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  note text NOT NULL DEFAULT '',
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.class_money_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id uuid NOT NULL REFERENCES public.class_money_books(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('income', 'expense', 'refund', 'adjustment')),
  amount bigint NOT NULL CHECK (amount >= 0),
  profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  collection_id uuid REFERENCES public.class_money_collections(id) ON DELETE SET NULL,
  expense_id uuid REFERENCES public.class_money_expenses(id) ON DELETE SET NULL,
  description text NOT NULL DEFAULT '',
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.class_money_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id uuid NOT NULL REFERENCES public.class_money_books(id) ON DELETE CASCADE,
  actor_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS class_money_members_book_idx ON public.class_money_members (book_id);
CREATE INDEX IF NOT EXISTS class_money_members_profile_idx ON public.class_money_members (profile_id);
CREATE INDEX IF NOT EXISTS class_money_collections_book_idx ON public.class_money_collections (book_id, created_at DESC);
CREATE INDEX IF NOT EXISTS class_money_collection_members_collection_idx ON public.class_money_collection_members (collection_id);
CREATE UNIQUE INDEX IF NOT EXISTS class_money_collection_members_profile_uidx
  ON public.class_money_collection_members (collection_id, profile_id)
  WHERE profile_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS class_money_collection_members_stt_uidx
  ON public.class_money_collection_members (collection_id, student_number)
  WHERE student_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS class_money_collection_members_profile_idx ON public.class_money_collection_members (profile_id);
CREATE INDEX IF NOT EXISTS class_money_expenses_book_spent_idx ON public.class_money_expenses (book_id, spent_at DESC);
CREATE INDEX IF NOT EXISTS class_money_transactions_book_created_idx ON public.class_money_transactions (book_id, created_at DESC);
CREATE INDEX IF NOT EXISTS class_money_audit_logs_book_created_idx ON public.class_money_audit_logs (book_id, created_at DESC);

ALTER TABLE public.class_money_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_money_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_money_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_money_collection_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_money_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_money_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_money_audit_logs ENABLE ROW LEVEL SECURITY;

-- Không mở quyền query trực tiếp cho anon/authenticated. Service role backend là lớp API duy nhất.
REVOKE ALL ON TABLE public.class_money_books, public.class_money_members,
  public.class_money_collections, public.class_money_collection_members,
  public.class_money_expenses, public.class_money_transactions,
  public.class_money_audit_logs FROM anon, authenticated;
