export function ContextMenu({ point, target, onClose, onAction }) {
  if (!point) return null
  const items = target === 'slide' ? [['new-slide', 'New Slide'], ['duplicate-slide', 'Duplicate Slide'], ['delete-slide', 'Delete Slide'], ['rename-slide', 'Rename Slide']] : [['duplicate', 'Duplicate Object'], ['delete', 'Delete Object'], ['front', 'Bring to Front'], ['back', 'Send to Back'], ['group', 'Group Selection'], ['lock', 'Lock Object']]
  return <div className="presentation-context-menu" style={{ left: point.x, top: point.y }} onMouseDown={(event) => event.stopPropagation()}>{items.map(([id, label]) => <button type="button" key={id} onClick={() => { onAction(id); onClose() }}>{label}</button>)}</div>
}

export function TableChartPanel({ element, onUpdate }) {
  if (!element || !['table', 'chart'].includes(element.type)) return null
  if (element.type === 'table') return <section className="presentation-data-panel"><div className="presentation-panel-title">TABLE DATA</div><div className="presentation-data-grid">{element.rows?.map((row, rowIndex) => row.map((cell, cellIndex) => <input key={`${rowIndex}-${cellIndex}`} value={cell} onChange={(event) => { const rows = element.rows.map((currentRow) => [...currentRow]); rows[rowIndex][cellIndex] = event.target.value; onUpdate({ rows }) }} />))}</div><div className="presentation-inline-buttons"><button type="button" onClick={() => onUpdate({ rows: [...element.rows, Array(element.rows[0]?.length || 2).fill('New')] })}>Insert Row</button><button type="button" onClick={() => onUpdate({ rows: element.rows.slice(0, -1) })} disabled={element.rows.length < 2}>Delete Row</button></div></section>
  return <section className="presentation-data-panel"><div className="presentation-panel-title">CHART DATA</div><label>Title<input value={element.title || ''} onChange={(event) => onUpdate({ title: event.target.value })} /></label><label>Type<select value={element.chartType || 'bar'} onChange={(event) => onUpdate({ chartType: event.target.value })}><option value="bar">Bar</option><option value="line">Line</option><option value="pie">Pie</option></select></label><div className="presentation-data-grid">{element.data?.map((item, index) => <div className="presentation-chart-input" key={item.label}><input value={item.label} onChange={(event) => { const data = [...element.data]; data[index] = { ...data[index], label: event.target.value }; onUpdate({ data }) }} /><input type="number" value={item.value} onChange={(event) => { const data = [...element.data]; data[index] = { ...data[index], value: Number(event.target.value) }; onUpdate({ data }) }} /></div>)}</div><div className="presentation-inline-buttons"><button type="button" onClick={() => onUpdate({ data: [...element.data, { label: `D${element.data.length + 1}`, value: 10 }] })}>Add Data</button><button type="button" onClick={() => onUpdate({ data: element.data.slice(0, -1) })} disabled={element.data.length < 2}>Remove Data</button></div></section>
}

export function TransitionPanel({ slide, onUpdate, onApplyAll }) {
  const transition = slide?.transition || { type: 'fade', duration: 0.5, advance: 'click' }
  return <section className="presentation-transition-panel"><div className="presentation-panel-title">TRANSITION</div><div className="presentation-transition-gallery">{['none', 'fade', 'push', 'wipe', 'zoom'].map((type) => <button type="button" className={transition.type === type ? 'is-active' : ''} key={type} onClick={() => onUpdate({ transition: { ...transition, type } })}><span className={`transition-preview transition-${type}`} />{type}</button>)}</div><label>Duration<input type="range" min="0" max="3" step=".1" value={transition.duration ?? .5} onChange={(event) => onUpdate({ transition: { ...transition, duration: Number(event.target.value) } })} /></label><label>Advance<select value={transition.advance || 'click'} onChange={(event) => onUpdate({ transition: { ...transition, advance: event.target.value } })}><option value="click">On click</option><option value="after">After duration</option></select></label><button type="button" onClick={onApplyAll}>Apply to all slides</button></section>
}
