import { useRef, useState } from 'react'

export default function SectionedSlideSidebar({ slides, sections, active, setActive, onNew, onDuplicate, onDelete, onReorder, onRenameSection, onToggleSection, onCreateSection, onMoveSlide, renderSlide }) {
  const dragSlide = useRef(null)
  const [editing, setEditing] = useState(null)
  const normalizedSections = sections?.length ? sections : [{ id: 'section-default', title: 'Section 1', collapsed: false }]
  const grouped = normalizedSections.map((section) => ({ ...section, items: slides.map((slide, index) => ({ slide, index })).filter(({ slide }) => (slide.sectionId || normalizedSections[0].id) === section.id) }))
  return <aside className="presentation-workspace-sidebar"><div className="presentation-sidebar-heading"><span>SECTIONS</span><button type="button" title="Create section" onClick={onCreateSection}>＋</button></div><div className="presentation-section-list">{grouped.map((section) => <section className="presentation-section-group" key={section.id}><header className="presentation-section-heading"><button type="button" className="presentation-section-toggle" onClick={() => onToggleSection(section.id)}>{section.collapsed ? '▸' : '▾'}</button>{editing === section.id ? <input autoFocus value={section.title} onChange={(event) => onRenameSection(section.id, event.target.value)} onBlur={() => setEditing(null)} onKeyDown={(event) => { if (event.key === 'Enter') setEditing(null) }} /> : <button type="button" className="presentation-section-name" onDoubleClick={() => setEditing(section.id)}>{section.title}</button>}<span>{section.items.length}</span><button type="button" className="presentation-section-add" title="Add slide to section" onClick={() => onNew(section.id)}>＋</button></header>{!section.collapsed ? <div className="presentation-slide-list">{section.items.map(({ slide, index }) => <div key={slide.id} className={`presentation-slide-thumb-wrap${active === index ? ' is-active' : ''}`} draggable onDragStart={() => { dragSlide.current = index }} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragSlide.current !== null) onReorder(dragSlide.current, index); dragSlide.current = null }}><button type="button" className="presentation-slide-thumb" onClick={() => setActive(index)}><span className="presentation-slide-number">{index + 1}</span><div className="presentation-slide-mini" style={{ background: slide.background?.value || '#fff' }}>{slide.elements?.map((element) => renderSlide(element))}</div><strong>{slide.title}</strong></button><div className="presentation-slide-actions"><button type="button" title="Move to section" onClick={() => onMoveSlide(index)}>↪</button><button type="button" onClick={() => onDuplicate(index)} aria-label="Nhân bản slide">⧉</button><button type="button" onClick={() => onDelete(index)} aria-label="Xóa slide">×</button></div></div>)}</div> : null}</section>)}</div></aside>
}
