import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext.jsx'
import { hasCapability } from '../lib/roles.js'
import { ROUTES } from '../lib/routes.js'
import * as resourceService from '../services/resourceService.js'
import './ResourcePage.css'

const formatBytes = (bytes) => { const n = Number(bytes) || 0; if (!n) return '—'; if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`; return `${(n / 1024 / 1024).toFixed(1)} MB` }
const imageAccept = 'image/jpeg,image/png,image/webp,image/gif,image/heic,image/heif'
const fileAccept = '.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.zip'

export default function ResourcePage({ embedded = false }) {
  const { authReady, session, profile } = useAuth(); const navigate = useNavigate(); const allowed = hasCapability(profile?.role, 'resourceManagement')
  const [categories, setCategories] = useState([]); const [resources, setResources] = useState([]); const [selected, setSelected] = useState(null)
  const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [fileType, setFileType] = useState(''); const [sort, setSort] = useState('newest')
  const [showCategory, setShowCategory] = useState(false); const [categoryForm, setCategoryForm] = useState({ name: '', description: '' }); const [editingCategory, setEditingCategory] = useState(null)
  const [showResource, setShowResource] = useState(false); const [resourceForm, setResourceForm] = useState({ title: '', description: '', note: '', category_id: '' }); const [editingResource, setEditingResource] = useState(null)
  const [files, setFiles] = useState([]); const [uploadFiles, setUploadFiles] = useState([]); const [lightbox, setLightbox] = useState(null); const [status, setStatus] = useState(navigator.onLine ? 'Online' : 'Offline'); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const load = useCallback(async () => { try { setError(''); const [cats, items] = await Promise.all([resourceService.getCategories(), resourceService.getResources({ search, category_id: category, file_type: fileType, sort })]); setCategories(cats); setResources(items); setSelected((old) => old ? items.find((x) => x.id === old.id) || null : null) } catch (e) { setError(e.message || 'Không tải được dữ liệu tài nguyên.') } }, [search, category, fileType, sort])
  useEffect(() => { if (authReady && session && allowed) load() }, [authReady, session, allowed, load])
  useEffect(() => { const online = () => { setStatus('Đang đồng bộ'); resourceService.syncQueue().then(() => { setStatus('Online'); load() }).catch(() => setStatus('Chờ đồng bộ')) }; const offline = () => setStatus('Offline'); window.addEventListener('online', online); window.addEventListener('offline', offline); const timer = setInterval(() => { if (navigator.onLine) resourceService.syncQueue().then(load).catch(() => {}) }, 30000); return () => { window.removeEventListener('online', online); window.removeEventListener('offline', offline); clearInterval(timer) } }, [load])
  const filtered = useMemo(() => resources, [resources])
  const closeResource = () => { setShowResource(false); setEditingResource(null); setFiles([]); setUploadFiles([]) }
  const saveCategory = async (event) => { event.preventDefault(); try { const item = await resourceService.saveCategory(categoryForm, editingCategory?.id); setCategories((old) => editingCategory ? old.map((x) => x.id === item.id ? item : x) : [...old, item]); setCategoryForm({ name: '', description: '' }); setEditingCategory(null); setShowCategory(false); setMessage('Đã lưu hạng mục.') } catch (e) { setError(e.message) } }
  const saveResource = async (event) => { event.preventDefault(); try { const item = await resourceService.saveResource(resourceForm, editingResource?.id); const pendingFiles = [...uploadFiles, ...files]; if (pendingFiles.length && !String(item.id).startsWith('local-')) { const added = await resourceService.uploadResourceFiles(item.id, pendingFiles); item.resource_files = added } else if (pendingFiles.length) await resourceService.uploadResourceFiles(item.id, pendingFiles); setMessage(navigator.onLine ? 'Đã lưu tài nguyên.' : 'Đã lưu cục bộ, sẽ tự đồng bộ khi có mạng.'); closeResource(); await load() } catch (e) { setError(e.message || 'Không lưu được tài nguyên.') } }
  const removeResource = async (item) => { if (!window.confirm(`Xóa tài nguyên “${item.title}”?`)) return; try { await resourceService.deleteResource(item.id); setSelected(null); setMessage(navigator.onLine ? 'Đã xóa tài nguyên.' : 'Đã xếp thao tác xóa vào hàng đợi.'); await load() } catch (e) { setError(e.message) } }
  const removeFile = async (file) => { try { await resourceService.deleteFile(file.id); setSelected((old) => old ? { ...old, resource_files: old.resource_files.filter((x) => x.id !== file.id) } : old); setMessage('Đã xóa file.') } catch (e) { setError(e.message) } }
  if (!authReady) return <main className={`resource-page${embedded ? ' resource-page--embedded' : ''}`}><div className="resource-state">Đang kiểm tra quyền...</div></main>
  if (!session) return <main className={`resource-page${embedded ? ' resource-page--embedded' : ''}`}><div className="resource-state"><h2>Cần đăng nhập</h2><button onClick={() => navigate(ROUTES.login)}>Đăng nhập</button></div></main>
  if (!allowed) return <main className={`resource-page${embedded ? ' resource-page--embedded' : ''}`}><div className="resource-state"><h2>Bạn không có quyền truy cập Quản lý tài nguyên.</h2><button onClick={() => navigate(ROUTES.home)}>Về trang chủ</button></div></main>
  return <main className={`resource-page${embedded ? ' resource-page--embedded' : ''}`}>
    <header className="resource-header"><div><p className="resource-eyebrow">Kho độc lập · {status}</p><h1>Quản lý tài nguyên</h1><p>Tài liệu, ảnh, code và file dùng chung của lớp.</p></div>{!embedded && <button className="resource-secondary" onClick={() => navigate(ROUTES.home)}>Về trang chủ</button>}</header>
    {message && <div className="resource-alert success">{message}<button onClick={() => setMessage('')}>×</button></div>}{error && <div className="resource-alert error">{error}<button onClick={() => setError('')}>×</button></div>}
    <section className="resource-toolbar"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm theo tên, mô tả, ghi chú..." /><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Tất cả hạng mục</option>{categories.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={fileType} onChange={(e) => setFileType(e.target.value)}><option value="">Mọi loại</option><option value="image">Có ảnh</option><option value="file">Có file</option></select><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="newest">Mới nhất</option><option value="oldest">Cũ nhất</option></select><button onClick={() => { setEditingCategory(null); setCategoryForm({ name: '', description: '' }); setShowCategory(true) }}>+ Tạo hạng mục</button><button className="resource-primary" onClick={() => { setEditingResource(null); setResourceForm({ title: '', description: '', note: '', category_id: '' }); setUploadFiles([]); setShowResource(true) }}>+ Tạo tài nguyên</button></section>
    <div className="resource-layout"><aside className="resource-categories"><h3>Hạng mục</h3>{categories.map((x) => <div className="category-row" key={x.id}><button onClick={() => setCategory(x.id)}>{x.name}<small>{x.resource_count || 0}</small></button><button className="icon-button" onClick={() => { setEditingCategory(x); setCategoryForm({ name: x.name, description: x.description || '' }); setShowCategory(true) }}>⋯</button></div>)}</aside><section className="resource-grid">{filtered.length ? filtered.map((item) => <article className="resource-card" key={item.id} onClick={() => setSelected(item)}><div className="resource-card-icon">{item.resource_files?.some((x) => x.file_type === 'image') ? '▧' : '▤'}</div><h3>{item.title} {item._local && <small className="resource-pending-badge">{item.sync_status === 'syncing' ? 'Đang đồng bộ' : 'Chờ đồng bộ'}</small>}</h3><span>{item.resource_categories?.name || 'Chưa phân loại'}</span><p>{item.description || 'Không có mô tả.'}</p><small>{item.resource_files?.length || 0} tệp · {item.created_at ? new Date(item.created_at).toLocaleDateString('vi-VN') : 'cục bộ'}</small></article>) : <div className="resource-empty">Chưa có tài nguyên phù hợp.</div>}</section></div>
    {selected && <div className="resource-overlay" onClick={() => setSelected(null)}><article className="resource-detail" onClick={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setSelected(null)}>×</button><p className="resource-eyebrow">{selected.resource_categories?.name || 'Tài nguyên'} {selected._local && '· Chưa đồng bộ'}</p><h2>{selected.title}</h2><p>{selected.description}</p>{selected.note && <div className="resource-note"><strong>Ghi chú</strong><p>{selected.note}</p></div>}<div className="resource-files">{(selected.resource_files || []).map((file) => file.file_type === 'image' ? <figure key={file.id}><button onClick={() => setLightbox(file)}><img src={file.url} alt={file.file_name} /></button><figcaption>{file.file_name} {file._local && <small>· Chờ đồng bộ</small>} <button onClick={() => removeFile(file)}>Xóa</button></figcaption></figure> : <div className="resource-file-row" key={file.id}><span>▣ {file.file_name}</span><small>{file.mime_type} · {formatBytes(file.size_bytes)} {file._local && '· Chờ đồng bộ'}</small><a href={file.url} target="_blank" rel="noreferrer">Xem / tải</a><button onClick={() => removeFile(file)}>Xóa</button></div>)}</div><div className="resource-detail-actions"><button onClick={() => { setEditingResource(selected); setResourceForm({ title: selected.title, description: selected.description || '', note: selected.note || '', category_id: selected.category_id || '' }); setSelected(null); setShowResource(true) }}>Sửa</button><button className="danger" onClick={() => removeResource(selected)}>Xóa tài nguyên</button></div></article></div>}
    {lightbox && <div className="resource-lightbox" onClick={() => setLightbox(null)}><img src={lightbox.url} alt={lightbox.file_name} /></div>}
    {showCategory && <div className="resource-modal"><form onSubmit={saveCategory}><h2>{editingCategory ? 'Sửa hạng mục' : 'Tạo hạng mục'}</h2><input required placeholder="Tên hạng mục" value={categoryForm.name} onChange={(e) => setCategoryForm({ ...categoryForm, name: e.target.value })} /><textarea placeholder="Mô tả" value={categoryForm.description} onChange={(e) => setCategoryForm({ ...categoryForm, description: e.target.value })} /><div><button type="button" onClick={() => setShowCategory(false)}>Hủy</button><button className="resource-primary">Lưu</button></div></form></div>}
    {showResource && <div className="resource-modal"><form onSubmit={saveResource}><h2>{editingResource ? 'Sửa tài nguyên' : 'Tạo tài nguyên'}</h2><input required placeholder="Tên tài nguyên" value={resourceForm.title} onChange={(e) => setResourceForm({ ...resourceForm, title: e.target.value })} /><select value={resourceForm.category_id} onChange={(e) => setResourceForm({ ...resourceForm, category_id: e.target.value })}><option value="">Chưa phân loại</option>{categories.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><textarea placeholder="Mô tả" value={resourceForm.description} onChange={(e) => setResourceForm({ ...resourceForm, description: e.target.value })} /><textarea placeholder="Ghi chú dài" value={resourceForm.note} onChange={(e) => setResourceForm({ ...resourceForm, note: e.target.value })} /><label>File đính kèm<input type="file" multiple accept={fileAccept} onChange={(e) => setUploadFiles([...e.target.files])} /></label><label>Ảnh đính kèm<input type="file" multiple accept={imageAccept} onChange={(e) => setFiles([...e.target.files])} /></label>{(files.length || uploadFiles.length) ? <p className="resource-selection">Đã chọn {files.length + uploadFiles.length} file/ảnh</p> : null}<div><button type="button" onClick={closeResource}>Hủy</button><button className="resource-primary">Lưu tài nguyên</button></div></form></div>}
  </main>
}
