import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import SiteHeader from '../components/SiteHeader.jsx'
import { getRoom, joinRoom, startRoom, submitAnswer } from '../services/gameRoomService.js'
import { ROUTES } from '../lib/routes.js'
import '../game.css'

function Board({ room }) { const length = room.settings.board_length; const cells = Array.from({ length }, (_, i) => i + 1); return <div className="board-wrap"><div className="board"><div className="board-row board-start"><span className="board-start-label">START</span>{cells.slice(0, 5).map((n) => <span className="board-cell" key={n}>{n}</span>)}</div>{Array.from({ length: Math.ceil((length - 5) / 5) }, (_, row) => { const nums = cells.slice(5 + row * 5, 10 + row * 5); if (!nums.length) return null; const list = row % 2 ? [...nums].reverse() : nums; return <div className="board-row" key={row}>{list.map((n) => <span className="board-cell" key={n}>{n}{room.teams.filter((team) => team.position === n).map((team) => <em className={`token token-${team.token}`} key={team.id} title={team.name}>{team.name.slice(-1)}</em>)}</span>)}</div> })}<span className="treasure">🏆</span></div></div> }

export default function RoomPage() {
  const { code } = useParams(); const [room, setRoom] = useState(null); const [answer, setAnswer] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [joined, setJoined] = useState(false)
  const refresh = () => getRoom(code).then(setRoom).catch((e) => setError(e.message)); useEffect(() => { refresh(); const timer = setInterval(refresh, 5000); return () => clearInterval(timer) }, [code])
  const currentTeam = useMemo(() => room?.teams?.[room.game?.current_turn || 0], [room]); const submit = async (e) => { e.preventDefault(); setBusy(true); try { setRoom(await submitAnswer(code, { answer, response_time_ms: 5000 })); setAnswer('') } catch (e2) { setError(e2.message) } finally { setBusy(false) } }
  if (!room) return <div className="game-shell"><SiteHeader /><main className="container game-main"><div className="game-panel">{error || 'Đang tải phòng...'}</div></main></div>
  const isLobby = room.status === 'lobby'; const isFinished = room.status === 'finished'
  return <div className="game-shell"><SiteHeader /><main className="container game-main"><div className="room-top"><div><p className="game-overline">Phòng chơi</p><h1>{room.settings?.title || 'Đua tới kho báu'}</h1></div><div className="room-code"><small>MÃ PHÒNG</small><strong>{room.code}</strong><button onClick={() => navigator.clipboard?.writeText(room.code)}>📋 Sao chép</button></div></div>
    {isLobby && <section className="lobby-grid"><div className="game-panel"><div className="panel-title"><h2>Phòng chờ</h2><span className="live-pill">● LIVE</span></div><p className="game-muted">Chia sẻ mã phòng để mọi người tham gia. Host có thể bắt đầu khi có ít nhất 2 đội.</p><div className="team-list">{room.teams.map((team) => <div className="team-row" key={team.id}><span className={`team-token token-${team.token}`} /> <strong>{team.name}</strong><small>{room.players.filter((p) => p.team_id === team.id).length} người chơi</small></div>)}</div>{room.is_host && <button className="game-button primary full" onClick={async () => { setBusy(true); try { setRoom(await startRoom(code)) } catch (e) { setError(e.message) } finally { setBusy(false) } }} disabled={busy}>{busy ? 'Đang xác định thứ tự...' : '▶ Bắt đầu game'}</button>}<button className="game-button quiet full" onClick={async () => { try { setRoom(await joinRoom(code)); setJoined(true) } catch (e) { setError(e.message) } }}>{joined ? 'Đã tham gia' : 'Tham gia phòng'}</button>{error && <div className="error-banner">{error}</div>}</div><div className="game-panel rules-panel"><h2>Luật chơi</h2><div className="rule-line">⚡ Đúng nhanh <b>+3 ô</b></div><div className="rule-line">✓ Đúng nhưng chậm <b>+2 ô</b></div><div className="rule-line">✕ Sai <b>-1 ô</b></div><div className="rule-line">🏆 Về đích <b>{room.settings.board_length} ô</b></div></div></section>}
    {!isLobby && <section className="play-layout"><div className="play-main"><div className="turn-banner">{isFinished ? '🏆 KHO BÁU ĐÃ ĐƯỢC TÌM THẤY!' : `🔵 ĐẾN LƯỢT ${currentTeam?.name || ''}`}</div><Board room={room} />{!isFinished && room.question && <form className="question-card" onSubmit={submit}><div className="question-meta">Câu hỏi {room.game.question_index + 1} / {room.game.total_questions}</div><h2>{room.question.content}</h2>{room.question.type === 'multiple_choice' ? <div className="answer-grid">{(room.question.options || []).map((option, index) => <button type="button" className={answer === String(index) ? 'answer-option selected' : 'answer-option'} key={option} onClick={() => setAnswer(String(index))}>{String.fromCharCode(65 + index)}. {option}</button>)}</div> : <div className="answer-grid"><button type="button" className={answer === 'true' ? 'answer-option selected' : 'answer-option'} onClick={() => setAnswer('true')}>Đúng</button><button type="button" className={answer === 'false' ? 'answer-option selected' : 'answer-option'} onClick={() => setAnswer('false')}>Sai</button></div>}<button className="game-button primary full" disabled={!answer || busy}>{busy ? 'Đang chấm...' : '🔒 Khóa đáp án'}</button></form>}</div><aside className="score-panel game-panel"><h2>Bảng xếp hạng</h2>{room.teams.map((team) => <div className="score-row" key={team.id}><span className={`team-token token-${team.token}`} /><div><strong>{team.name}</strong><small>{team.position} / {room.settings.board_length} ô</small></div><b>{team.correct_count}</b></div>)}{isFinished && <Link className="game-button quiet full" to={ROUTES.home}>🏠 Về trang chủ</Link>}</aside></section>}
  </main></div>
}
