-- =====================================================================
-- Bài KIỂM TRA online (Bài tập về nhà → Kiểm tra; Quản lý lớp → Kiểm tra)
-- Chạy file này 1 lần trong Supabase → SQL Editor.
-- Mẫu theo homework_direct_upload.sql: file nằm ở Storage (bucket
-- classroom-data, private), Postgres chỉ lưu metadata.
-- Đồng hồ làm bài chạy Ở SERVER (class_exam_attempts.deadline_at) nên thoát
-- ra vào lại, đổi máy, tắt app… vẫn đếm tiếp.
-- =====================================================================

create table if not exists public.class_exams (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null default '',
  images jsonb not null default '[]'::jsonb,         -- [{path,name,mime,size}] ảnh đề
  duration_minutes integer not null check (duration_minutes between 1 and 600),
  open_at timestamptz not null,                      -- bắt đầu mở đề
  close_at timestamptz not null,                     -- hạn chót (hết hạn là không bấm bắt đầu/nộp được nữa)
  created_by uuid references public.profiles(id) on delete set null,
  created_by_name text,
  created_at timestamptz not null default now(),
  check (close_at > open_at)
);
create index if not exists class_exams_open_idx on public.class_exams(open_at desc);

-- 1 học sinh – 1 lượt làm / đề. deadline_at = min(started_at + thời gian làm, close_at)
create table if not exists public.class_exam_attempts (
  id uuid primary key default gen_random_uuid(),
  exam_id uuid not null references public.class_exams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  started_at timestamptz not null default now(),
  deadline_at timestamptz not null,
  unique (exam_id, user_id)
);
create index if not exists class_exam_attempts_exam_idx on public.class_exam_attempts(exam_id);

create table if not exists public.class_exam_submissions (
  id uuid primary key default gen_random_uuid(),
  exam_id uuid not null references public.class_exams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  user_name text,
  files jsonb not null default '[]'::jsonb,
  submitted_at timestamptz not null default now(),
  unique (exam_id, user_id)
);
create index if not exists class_exam_submissions_exam_idx on public.class_exam_submissions(exam_id);

create table if not exists public.class_exam_upload_intents (
  id uuid primary key default gen_random_uuid(),
  exam_id uuid not null references public.class_exams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 minutes')
);
create index if not exists class_exam_upload_intents_user_idx on public.class_exam_upload_intents(user_id, expires_at);

create table if not exists public.class_exam_upload_intent_files (
  id bigint generated by default as identity primary key,
  intent_id uuid not null references public.class_exam_upload_intents(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 31457280), -- 30MB (PDF); ảnh bị giới hạn 10MB ở backend
  created_at timestamptz not null default now()
);
create index if not exists class_exam_upload_intent_files_idx on public.class_exam_upload_intent_files(intent_id);

-- Chỉ backend (service_role) được đụng vào; trình duyệt không truy cập trực tiếp.
alter table public.class_exams enable row level security;
alter table public.class_exam_attempts enable row level security;
alter table public.class_exam_submissions enable row level security;
alter table public.class_exam_upload_intents enable row level security;
alter table public.class_exam_upload_intent_files enable row level security;
revoke all on public.class_exams, public.class_exam_attempts, public.class_exam_submissions,
  public.class_exam_upload_intents, public.class_exam_upload_intent_files from anon, authenticated;
grant all on public.class_exams, public.class_exam_attempts, public.class_exam_submissions,
  public.class_exam_upload_intents, public.class_exam_upload_intent_files to service_role;

-- Tóm tắt cho danh sách đề: số bài đã nộp + lượt làm / bài nộp của chính mình
create or replace function public.class_exam_summary(p_exam_ids uuid[], p_user_id uuid default null)
returns table(exam_id uuid, submitted_count bigint, my_started_at timestamptz,
              my_deadline_at timestamptz, my_submitted_at timestamptz, my_file_count integer)
language sql
security definer
set search_path = public, pg_temp
as $$
  select e.id,
    (select count(*) from public.class_exam_submissions s where s.exam_id = e.id),
    a.started_at, a.deadline_at, s2.submitted_at,
    coalesce(jsonb_array_length(s2.files), 0)
  from public.class_exams e
  left join public.class_exam_attempts a on a.exam_id = e.id and a.user_id = p_user_id
  left join public.class_exam_submissions s2 on s2.exam_id = e.id and s2.user_id = p_user_id
  where e.id = any(coalesce(p_exam_ids, '{}'::uuid[]))
$$;
revoke all on function public.class_exam_summary(uuid[], uuid) from public, anon, authenticated;
grant execute on function public.class_exam_summary(uuid[], uuid) to service_role;

-- Bấm "Bắt đầu làm bài": tạo lượt làm (idempotent – bấm lại / vào lại không reset đồng hồ)
create or replace function public.class_exam_start(p_exam_id uuid, p_user_id uuid)
returns table(started_at timestamptz, deadline_at timestamptz, server_now timestamptz)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_exam public.class_exams%rowtype;
  v_now timestamptz := now();
begin
  select * into v_exam from public.class_exams where id = p_exam_id;
  if not found then raise exception using errcode = 'P0002', message = 'EXAM_NOT_FOUND'; end if;

  -- đã có lượt làm thì trả về luôn (dù đề đã đóng) để vào lại được
  return query
    select a.started_at, a.deadline_at, v_now
    from public.class_exam_attempts a where a.exam_id = p_exam_id and a.user_id = p_user_id;
  if found then return; end if;

  if v_now < v_exam.open_at then raise exception using errcode = 'P0001', message = 'EXAM_NOT_OPEN'; end if;
  if v_now >= v_exam.close_at then raise exception using errcode = 'P0001', message = 'EXAM_CLOSED'; end if;

  insert into public.class_exam_attempts(exam_id, user_id, started_at, deadline_at)
  values (p_exam_id, p_user_id, v_now,
          least(v_now + make_interval(mins => v_exam.duration_minutes), v_exam.close_at))
  on conflict (exam_id, user_id) do nothing;

  return query
    select a.started_at, a.deadline_at, v_now
    from public.class_exam_attempts a where a.exam_id = p_exam_id and a.user_id = p_user_id;
end;
$$;
revoke all on function public.class_exam_start(uuid, uuid) from public, anon, authenticated;
grant execute on function public.class_exam_start(uuid, uuid) to service_role;

-- Chốt bài nộp (nguyên tử). Chỉ cho nộp khi còn trong deadline.
-- Ngoại lệ 90 giây: file đã BẮT ĐẦU tải lên trước giờ hết hạn thì vẫn được chốt (mạng chậm).
create or replace function public.class_exam_commit_submission(
  p_intent_id uuid, p_user_id uuid, p_user_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_intent public.class_exam_upload_intents%rowtype;
  v_attempt public.class_exam_attempts%rowtype;
  v_old_files jsonb := '[]'::jsonb;
  v_files jsonb;
  v_total bigint;
  v_submitted_at timestamptz := now();
begin
  select * into v_intent from public.class_exam_upload_intents
    where id = p_intent_id and user_id = p_user_id for update;
  if not found or v_intent.expires_at <= now() then
    raise exception using errcode = 'P0001', message = 'UPLOAD_INTENT_EXPIRED';
  end if;

  select * into v_attempt from public.class_exam_attempts
    where exam_id = v_intent.exam_id and user_id = p_user_id;
  if not found then raise exception using errcode = 'P0001', message = 'EXAM_NOT_STARTED'; end if;

  if v_intent.created_at > v_attempt.deadline_at
     or now() > v_attempt.deadline_at + interval '90 seconds' then
    raise exception using errcode = 'P0001', message = 'EXAM_TIME_UP';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
      'path', storage_path, 'name', original_name, 'mime', mime_type, 'size', size_bytes
    ) order by id), '[]'::jsonb), coalesce(sum(size_bytes), 0)
  into v_files, v_total
  from public.class_exam_upload_intent_files where intent_id = p_intent_id;

  if jsonb_array_length(v_files) < 1 or jsonb_array_length(v_files) > 20 or v_total > 52428800 then
    raise exception using errcode = 'P0001', message = 'INVALID_UPLOAD_MANIFEST';
  end if;

  select files into v_old_files from public.class_exam_submissions
    where exam_id = v_intent.exam_id and user_id = p_user_id for update;

  insert into public.class_exam_submissions(exam_id, user_id, user_name, files, submitted_at)
    values (v_intent.exam_id, p_user_id, nullif(p_user_name, ''), v_files, v_submitted_at)
    on conflict (exam_id, user_id) do update set
      user_name = excluded.user_name, files = excluded.files, submitted_at = excluded.submitted_at;

  delete from public.class_exam_upload_intents where id = p_intent_id;
  return jsonb_build_object('exam_id', v_intent.exam_id, 'submitted_at', v_submitted_at,
    'file_count', jsonb_array_length(v_files), 'old_files', coalesce(v_old_files, '[]'::jsonb));
end;
$$;
revoke all on function public.class_exam_commit_submission(uuid, uuid, text) from public, anon, authenticated;
grant execute on function public.class_exam_commit_submission(uuid, uuid, text) to service_role;

notify pgrst, 'reload schema';
