-- Direct-to-Storage image uploads for cleaning duty. Binary data remains in classroom-data.
-- Run after cleaning-duty-media-schema.sql.
create table if not exists public.cleaning_duty_upload_intents (
  id uuid primary key default gen_random_uuid(),
  week_start date not null,
  duty_date date not null,
  day_id text not null check (day_id in ('t2','t3','t4','t5','t6','t7')),
  uploaded_by uuid not null references public.profiles(id) on delete cascade,
  uploaded_by_name text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  check (duty_date between week_start and week_start + 5)
);
create index if not exists cleaning_duty_upload_intents_owner_expiry_idx
  on public.cleaning_duty_upload_intents(uploaded_by, expires_at);
create table if not exists public.cleaning_duty_upload_intent_files (
  id bigint generated by default as identity primary key,
  intent_id uuid not null references public.cleaning_duty_upload_intents(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text not null check (mime_type in ('image/jpeg','image/png','image/webp','image/gif','image/heic','image/heif')),
  size_bytes integer not null check (size_bytes > 0 and size_bytes <= 26214400),
  created_at timestamptz not null default now()
);
create index if not exists cleaning_duty_upload_intent_files_intent_idx
  on public.cleaning_duty_upload_intent_files(intent_id);
alter table public.cleaning_duty_upload_intents enable row level security;
alter table public.cleaning_duty_upload_intent_files enable row level security;
revoke all on public.cleaning_duty_upload_intents, public.cleaning_duty_upload_intent_files from anon, authenticated;
grant all on public.cleaning_duty_upload_intents, public.cleaning_duty_upload_intent_files to service_role;
notify pgrst, 'reload schema';
