-- Relational timetable state. The legacy classroom_store row is retained as an
-- immutable source. Existing production public.timetables.id is BIGINT; do not
-- alter its type or copy arbitrary legacy JSON IDs into it.
-- The explicit transaction makes a failed rerun atomic. It is intentionally safe
-- whether an earlier SQL-editor attempt rolled back entirely or left objects.
begin;

create table if not exists public.timetables (
  id bigint generated by default as identity primary key,
  class_name text not null,
  effective_from date,
  subjects jsonb not null default '[]'::jsonb,
  days jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add only absent fields. In particular, the existing BIGINT id column is never
-- changed. Extra production columns such as morning_meta/afternoon_meta remain.
alter table public.timetables add column if not exists class_name text;
alter table public.timetables add column if not exists effective_from date;
alter table public.timetables add column if not exists subjects jsonb;
alter table public.timetables add column if not exists days jsonb;
alter table public.timetables add column if not exists created_at timestamptz;
alter table public.timetables add column if not exists updated_at timestamptz;

do $$
declare
  id_type text;
  parent_attnum smallint;
  has_unique_id boolean;
  missing_class_names bigint;
begin
  select format_type(a.atttypid, a.atttypmod), a.attnum
    into id_type, parent_attnum
  from pg_attribute a
  where a.attrelid='public.timetables'::regclass
    and a.attname='id' and a.attnum > 0 and not a.attisdropped;
  if id_type is distinct from 'bigint' then
    raise exception 'public.timetables.id must remain BIGINT; found %. No conversion was attempted.', coalesce(id_type, '<missing>');
  end if;

  select exists (
    select 1 from pg_index i
    where i.indrelid='public.timetables'::regclass
      and i.indisunique and i.indisvalid and i.indpred is null and i.indexprs is null
      and i.indnkeyatts=1 and i.indnatts=1 and i.indkey[0]=parent_attnum
  ) into has_unique_id;
  if not has_unique_id then
    raise exception 'public.timetables.id must have an existing PRIMARY KEY/UNIQUE constraint; inspect the live table before continuing.';
  end if;

  select count(*) into missing_class_names from public.timetables
    where class_name is null or btrim(class_name)='';
  if missing_class_names > 0 then
    raise exception 'public.timetables has % NULL/blank class_name rows; review them without overwriting existing data.', missing_class_names;
  end if;
end $$;

-- These defaults only affect future rows. Existing NULL JSON/timestamps are
-- repaired to the same neutral values used by the old migration; identifiers
-- and non-NULL production values are untouched.
update public.timetables set subjects='[]'::jsonb where subjects is null;
update public.timetables set days='[]'::jsonb where days is null;
update public.timetables set created_at=now() where created_at is null;
update public.timetables set updated_at=now() where updated_at is null;
alter table public.timetables alter column class_name set not null;
alter table public.timetables alter column subjects set default '[]'::jsonb;
alter table public.timetables alter column subjects set not null;
alter table public.timetables alter column days set default '[]'::jsonb;
alter table public.timetables alter column days set not null;
alter table public.timetables alter column created_at set default now();
alter table public.timetables alter column created_at set not null;
alter table public.timetables alter column updated_at set default now();
alter table public.timetables alter column updated_at set not null;
-- Child tables deliberately declare timetable_id as BIGINT, without an inline
-- FK. The separate catalog-checked FK block below handles partial installations
-- and gives an explicit error for any old UUID child column.
create table if not exists public.timetable_sessions (
  id uuid primary key default gen_random_uuid(),
  timetable_id bigint not null,
  session text not null check (session in ('morning', 'afternoon')),
  label text not null default '',
  days_note text not null default '',
  arrival text not null default '',
  has_flag_ceremony boolean not null default false,
  flag_ceremony_configured boolean not null default false,
  flag_ceremony_time text,
  flag_ceremony_note text
);
alter table public.timetable_sessions add column if not exists timetable_id bigint;
alter table public.timetable_sessions add column if not exists session text;
alter table public.timetable_sessions add column if not exists label text;
alter table public.timetable_sessions add column if not exists days_note text;
alter table public.timetable_sessions add column if not exists arrival text;
alter table public.timetable_sessions add column if not exists has_flag_ceremony boolean;
alter table public.timetable_sessions add column if not exists flag_ceremony_configured boolean;
alter table public.timetable_sessions add column if not exists flag_ceremony_time text;
alter table public.timetable_sessions add column if not exists flag_ceremony_note text;
update public.timetable_sessions set label='' where label is null;
update public.timetable_sessions set days_note='' where days_note is null;
update public.timetable_sessions set arrival='' where arrival is null;
update public.timetable_sessions set has_flag_ceremony=false where has_flag_ceremony is null;
update public.timetable_sessions set flag_ceremony_configured=false where flag_ceremony_configured is null;
alter table public.timetable_sessions alter column label set default '';
alter table public.timetable_sessions alter column label set not null;
alter table public.timetable_sessions alter column days_note set default '';
alter table public.timetable_sessions alter column days_note set not null;
alter table public.timetable_sessions alter column arrival set default '';
alter table public.timetable_sessions alter column arrival set not null;
alter table public.timetable_sessions alter column has_flag_ceremony set default false;
alter table public.timetable_sessions alter column has_flag_ceremony set not null;
alter table public.timetable_sessions alter column flag_ceremony_configured set default false;
alter table public.timetable_sessions alter column flag_ceremony_configured set not null;

create table if not exists public.timetable_periods (
  id bigint generated by default as identity primary key,
  timetable_id bigint not null,
  session text not null check (session in ('morning', 'afternoon')),
  period_id integer not null check (period_id between 1 and 8),
  start_time time not null,
  end_time time not null,
  note text
);
alter table public.timetable_periods add column if not exists timetable_id bigint;
alter table public.timetable_periods add column if not exists session text;
alter table public.timetable_periods add column if not exists period_id integer;
alter table public.timetable_periods add column if not exists start_time time;
alter table public.timetable_periods add column if not exists end_time time;
alter table public.timetable_periods add column if not exists note text;
update public.timetable_periods set start_time='00:00' where start_time is null;
update public.timetable_periods set end_time='00:00' where end_time is null;
alter table public.timetable_periods alter column start_time set not null;
alter table public.timetable_periods alter column end_time set not null;

create table if not exists public.timetable_breaks (
  id bigint generated by default as identity primary key,
  timetable_id bigint not null,
  session text not null check (session in ('morning', 'afternoon')),
  after_period integer not null check (after_period between 1 and 8),
  start_time time not null,
  end_time time not null,
  label text not null default 'Giải lao'
);
alter table public.timetable_breaks add column if not exists timetable_id bigint;
alter table public.timetable_breaks add column if not exists session text;
alter table public.timetable_breaks add column if not exists after_period integer;
alter table public.timetable_breaks add column if not exists start_time time;
alter table public.timetable_breaks add column if not exists end_time time;
alter table public.timetable_breaks add column if not exists label text;
update public.timetable_breaks set start_time='00:00' where start_time is null;
update public.timetable_breaks set end_time='00:00' where end_time is null;
update public.timetable_breaks set label='Giải lao' where label is null;
alter table public.timetable_breaks alter column start_time set not null;
alter table public.timetable_breaks alter column end_time set not null;
alter table public.timetable_breaks alter column label set default 'Giải lao';
alter table public.timetable_breaks alter column label set not null;

create table if not exists public.timetable_entries (
  id bigint generated by default as identity primary key,
  timetable_id bigint not null,
  session text not null check (session in ('morning', 'afternoon')),
  day_id text not null check (day_id in ('t2', 't3', 't4', 't5', 't6', 't7')),
  period_id integer not null check (period_id between 1 and 8),
  subject text not null default ''
);
alter table public.timetable_entries add column if not exists timetable_id bigint;
alter table public.timetable_entries add column if not exists session text;
alter table public.timetable_entries add column if not exists day_id text;
alter table public.timetable_entries add column if not exists period_id integer;
alter table public.timetable_entries add column if not exists subject text;
update public.timetable_entries set subject='' where subject is null;
alter table public.timetable_entries alter column subject set default '';
alter table public.timetable_entries alter column subject set not null;

create table if not exists public.timetable_change_notices (
  id bigint generated by default as identity primary key,
  timetable_id bigint not null,
  active boolean not null default false,
  has_changes boolean not null default false,
  date_from date,
  date_to date,
  summary text not null default 'Chưa có sự thay đổi',
  lines jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.timetable_change_notices add column if not exists timetable_id bigint;
alter table public.timetable_change_notices add column if not exists active boolean;
alter table public.timetable_change_notices add column if not exists has_changes boolean;
alter table public.timetable_change_notices add column if not exists date_from date;
alter table public.timetable_change_notices add column if not exists date_to date;
alter table public.timetable_change_notices add column if not exists summary text;
alter table public.timetable_change_notices add column if not exists lines jsonb;
alter table public.timetable_change_notices add column if not exists created_at timestamptz;
update public.timetable_change_notices set active=false where active is null;
update public.timetable_change_notices set has_changes=false where has_changes is null;
update public.timetable_change_notices set summary='Chưa có sự thay đổi' where summary is null;
update public.timetable_change_notices set lines='[]'::jsonb where lines is null;
update public.timetable_change_notices set created_at=now() where created_at is null;
alter table public.timetable_change_notices alter column active set default false;
alter table public.timetable_change_notices alter column active set not null;
alter table public.timetable_change_notices alter column has_changes set default false;
alter table public.timetable_change_notices alter column has_changes set not null;
alter table public.timetable_change_notices alter column summary set default 'Chưa có sự thay đổi';
alter table public.timetable_change_notices alter column summary set not null;
alter table public.timetable_change_notices alter column lines set default '[]'::jsonb;
alter table public.timetable_change_notices alter column lines set not null;
alter table public.timetable_change_notices alter column created_at set default now();
alter table public.timetable_change_notices alter column created_at set not null;

-- Fail clearly on any incompatible or incomplete partial-state ID column; never
-- ALTER its type or replace its values. Each timetable_id FK must be BIGINT -> BIGINT; existing child IDs are preserved.
do $$
declare
  child_table text;
  child_id_type text;
  fk_type text;
  null_fk_rows bigint;
  invalid_key_rows bigint;
  parent_attnum smallint;
begin
  select attnum into parent_attnum from pg_attribute
  where attrelid='public.timetables'::regclass and attname='id' and attnum > 0 and not attisdropped;
  if parent_attnum is null then
    raise exception 'public.timetables.id is missing; no ID column was added or generated.';
  end if;

  foreach child_table in array array[
    'timetable_sessions','timetable_periods','timetable_breaks',
    'timetable_entries','timetable_change_notices'
  ] loop
    select format_type(a.atttypid,a.atttypmod) into child_id_type
    from pg_attribute a where a.attrelid=format('public.%I',child_table)::regclass
      and a.attname='id' and a.attnum > 0 and not a.attisdropped;
    if child_table = 'timetable_sessions' then
      if child_id_type is distinct from 'uuid' then
        raise exception 'public.%.id must remain UUID; found %. No conversion was attempted.', child_table, coalesce(child_id_type,'<missing>');
      end if;
    elsif child_id_type is distinct from 'bigint' then
      raise exception 'public.%.id must remain BIGINT; found %. No conversion was attempted.', child_table, coalesce(child_id_type,'<missing>');
    end if;

    select format_type(a.atttypid,a.atttypmod) into fk_type
    from pg_attribute a where a.attrelid=format('public.%I',child_table)::regclass
      and a.attname='timetable_id' and a.attnum > 0 and not a.attisdropped;
    if fk_type is distinct from 'bigint' then
      raise exception 'public.%.timetable_id must be BIGINT to match public.timetables.id; found %. No conversion or row deletion was attempted.',
        child_table, coalesce(fk_type,'<missing>');
    end if;

    execute format('select count(*) from public.%I where timetable_id is null',child_table) into null_fk_rows;
    if null_fk_rows > 0 then
      raise exception 'public.%.timetable_id has % NULL rows; inspect this partial table before adding its required FK.', child_table, null_fk_rows;
    end if;
    execute format('alter table public.%I alter column timetable_id set not null',child_table);
  end loop;

  if exists (select 1 from public.timetable_sessions where session is null) then
    raise exception 'public.timetable_sessions contains NULL session keys; inspect existing rows before retrying.';
  end if;
  if exists (select 1 from public.timetable_periods where session is null or period_id is null) then
    raise exception 'public.timetable_periods contains NULL natural-key values; inspect existing rows before retrying.';
  end if;
  if exists (select 1 from public.timetable_breaks where session is null or after_period is null) then
    raise exception 'public.timetable_breaks contains NULL natural-key values; inspect existing rows before retrying.';
  end if;
  if exists (select 1 from public.timetable_entries where session is null or day_id is null or period_id is null) then
    raise exception 'public.timetable_entries contains NULL natural-key values; inspect existing rows before retrying.';
  end if;
  select count(*) into invalid_key_rows from public.timetable_periods
    where period_id not between 1 and 8;
  if invalid_key_rows > 0 then
    raise exception 'public.timetable_periods has % period_id values outside 1..8; no rows were changed.', invalid_key_rows;
  end if;
  select count(*) into invalid_key_rows from public.timetable_breaks
    where after_period not between 1 and 8;
  if invalid_key_rows > 0 then
    raise exception 'public.timetable_breaks has % after_period values outside 1..8; no rows were changed.', invalid_key_rows;
  end if;
  select count(*) into invalid_key_rows from public.timetable_entries
    where period_id not between 1 and 8 or day_id not in ('t2','t3','t4','t5','t6','t7');
  if invalid_key_rows > 0 then
    raise exception 'public.timetable_entries has % invalid day/period key values; no rows were changed.', invalid_key_rows;
  end if;
end $$;

alter table public.timetable_sessions alter column session set not null;
alter table public.timetable_periods alter column session set not null;
alter table public.timetable_periods alter column period_id set not null;
alter table public.timetable_breaks alter column session set not null;
alter table public.timetable_breaks alter column after_period set not null;
alter table public.timetable_entries alter column session set not null;
alter table public.timetable_entries alter column day_id set not null;
alter table public.timetable_entries alter column period_id set not null;

-- Check existing FK definitions and add only the exact BIGINT -> BIGINT relation.
-- NOT VALID preserves historical orphan rows but enforces future writes.
do $$
declare
  child_table text;
  child_attnum smallint;
  parent_attnum smallint;
  wrong_fk boolean;
  incompatible_delete boolean;
begin
  select attnum into parent_attnum from pg_attribute
  where attrelid='public.timetables'::regclass and attname='id' and attnum > 0 and not attisdropped;

  foreach child_table in array array[
    'timetable_sessions','timetable_periods','timetable_breaks',
    'timetable_entries','timetable_change_notices'
  ] loop
    select attnum into child_attnum from pg_attribute
    where attrelid=format('public.%I',child_table)::regclass
      and attname='timetable_id' and attnum > 0 and not attisdropped;

    select exists (
      select 1 from pg_constraint c
      where c.conrelid=format('public.%I',child_table)::regclass and c.contype='f'
        and c.conkey=array[child_attnum]::smallint[]
        and (c.confrelid <> 'public.timetables'::regclass or c.confkey <> array[parent_attnum]::smallint[])
    ) into wrong_fk;
    if wrong_fk then
      raise exception 'public.%.timetable_id already has an unrelated FK; inspect it without dropping data.', child_table;
    end if;

    select exists (
      select 1 from pg_constraint c
      where c.conrelid=format('public.%I',child_table)::regclass and c.contype='f'
        and c.conkey=array[child_attnum]::smallint[]
        and c.confrelid='public.timetables'::regclass and c.confkey=array[parent_attnum]::smallint[]
        and c.confdeltype <> 'c'
    ) into incompatible_delete;
    if incompatible_delete then
      raise exception 'public.%.timetable_id references timetables.id but does not use ON DELETE CASCADE; inspect before retrying.', child_table;
    end if;

    if not exists (
      select 1 from pg_constraint c
      where c.conrelid=format('public.%I',child_table)::regclass and c.contype='f'
        and c.conkey=array[child_attnum]::smallint[]
        and c.confrelid='public.timetables'::regclass and c.confkey=array[parent_attnum]::smallint[]
    ) then
      execute format(
        'alter table public.%I add constraint %I foreign key (timetable_id) references public.timetables(id) on delete cascade not valid',
        child_table, child_table || '_timetable_id_fkey'
      );
    end if;
  end loop;
end $$;

-- Unique keys used by the backfill's ON CONFLICT targets. Duplicate legacy rows
-- cause an explicit index-creation error; the transaction rolls back, no rows are
-- deleted or merged. Existing equivalent unique indexes are reused.
do $$
declare
  expected record;
  rel regclass;
  key_attnums smallint[];
  has_unique boolean;
  key_count integer;
begin
  for expected in select * from (values
    ('timetables','timetables_class_name_uidx','class_name'),
    ('timetable_sessions','timetable_sessions_timetable_session_uidx','timetable_id,session'),
    ('timetable_periods','timetable_periods_timetable_session_period_uidx','timetable_id,session,period_id'),
    ('timetable_breaks','timetable_breaks_timetable_session_after_uidx','timetable_id,session,after_period'),
    ('timetable_entries','timetable_entries_timetable_session_day_period_uidx','timetable_id,session,day_id,period_id'),
    ('timetable_change_notices','timetable_change_notices_timetable_uidx','timetable_id')
  ) as expected(table_name,index_name,column_list)
  loop
    rel := to_regclass(format('public.%I',expected.table_name));
    select array_agg(a.attnum::smallint order by cols.ordinality)
      into key_attnums
    from unnest(string_to_array(expected.column_list,',')) with ordinality as cols(column_name,ordinality)
    join pg_attribute a on a.attrelid=rel and a.attname=cols.column_name
      and a.attnum > 0 and not a.attisdropped;
    key_count := cardinality(key_attnums);
    if key_count <> cardinality(string_to_array(expected.column_list,',')) then
      raise exception 'Cannot create %: a required key column is missing.', expected.index_name;
    end if;

    select exists (
      select 1 from pg_index i
      where i.indrelid=rel and i.indisunique and i.indisvalid
        and i.indpred is null and i.indexprs is null
        and i.indnkeyatts=key_count and i.indnatts=key_count
        and array(select i.indkey[positions.pos]::smallint
          from generate_series(0,key_count-1) as positions(pos))=key_attnums
    ) into has_unique;
    if not has_unique then
      execute format('create unique index %I on public.%I (%s)',
        expected.index_name,expected.table_name,expected.column_list);
    end if;
  end loop;
end $$;

create index if not exists timetable_sessions_timetable_idx on public.timetable_sessions (timetable_id, session);
create index if not exists timetable_periods_timetable_idx on public.timetable_periods (timetable_id, session, period_id);
create index if not exists timetable_breaks_timetable_idx on public.timetable_breaks (timetable_id, session, after_period);
create index if not exists timetable_entries_timetable_idx on public.timetable_entries (timetable_id, session, day_id, period_id);
create index if not exists timetable_notices_active_idx on public.timetable_change_notices (timetable_id, active, created_at desc);

-- The service reads key 'timetable' and identifies the relational root by
-- class_name. Any legacy JSON id (numeric, UUID-shaped, blank, or malformed) is
-- intentionally not cast or used; source_value remains intact in classroom_store.
do $$
declare
  source_value jsonb;
  source_session jsonb;
  source_notice jsonb;
  root_timetable_id bigint;
  class_name_value text;
  session_name text;
begin
  if to_regclass('public.classroom_store') is not null then
    execute 'select value from public.classroom_store where key = $1'
      into source_value using 'timetable';

    if jsonb_typeof(source_value) = 'object' then
      class_name_value := coalesce(nullif(btrim(source_value->>'className'), ''), '10A4');

      insert into public.timetables (class_name, effective_from, subjects, days, updated_at)
      values (
        class_name_value,
        case when pg_input_is_valid(source_value->>'effectiveFrom', 'date')
          then (source_value->>'effectiveFrom')::date else null end,
        case when jsonb_typeof(source_value->'subjects') = 'array' then source_value->'subjects' else '[]'::jsonb end,
        case when jsonb_typeof(source_value->'days') = 'array' then source_value->'days' else '[]'::jsonb end,
        case when pg_input_is_valid(source_value->>'updatedAt', 'timestamptz')
          then (source_value->>'updatedAt')::timestamptz else now() end
      ) on conflict (class_name) do nothing;

      select id into root_timetable_id from public.timetables where class_name=class_name_value;
      if root_timetable_id is null then
        raise exception 'Could not resolve BIGINT timetable id for legacy class_name %; source remains in classroom_store.', class_name_value;
      end if;

      foreach session_name in array array['morning'::text, 'afternoon'::text] loop
        source_session := case when jsonb_typeof(source_value->session_name)='object'
          then source_value->session_name else '{}'::jsonb end;
        insert into public.timetable_sessions (
          timetable_id,session,label,days_note,arrival,
          has_flag_ceremony,flag_ceremony_configured,flag_ceremony_time,flag_ceremony_note
        ) values (
          root_timetable_id,session_name,
          coalesce(source_session->>'label',''),
          coalesce(source_session->>'daysNote',''),
          case when source_session->>'arrival' ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then source_session->>'arrival' else '' end,
          coalesce(jsonb_typeof(source_session->'flagCeremony')='object',false),
          source_session ? 'flagCeremony',
          case when source_session->'flagCeremony'->>'time' ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
            then source_session->'flagCeremony'->>'time' else null end,
          nullif(source_session->'flagCeremony'->>'note','')
        ) on conflict (timetable_id,session) do nothing;

        insert into public.timetable_periods (timetable_id,session,period_id,start_time,end_time,note)
        select root_timetable_id,session_name,
          case when item->>'id' ~ '^[1-8]$' then (item->>'id')::smallint else ordinality::smallint end,
          case when item->>'start' ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then item->>'start' else '00:00' end,
          case when item->>'end' ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then item->>'end' else '00:00' end,
          nullif(item->>'note','')
        from jsonb_array_elements(
          case when jsonb_typeof(source_session->'periods')='array' then source_session->'periods' else '[]'::jsonb end
        ) with ordinality as periods(item,ordinality)
        where ordinality<=8
          and (nullif(btrim(item->>'id'),'') is null or item->>'id' ~ '^[1-8]$')
        on conflict (timetable_id,session,period_id) do nothing;

        insert into public.timetable_breaks (timetable_id,session,after_period,start_time,end_time,label)
        select root_timetable_id,session_name,
          case when item->>'after' ~ '^[1-8]$' then (item->>'after')::smallint else 2 end,
          case when item->>'start' ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then item->>'start' else '00:00' end,
          case when item->>'end' ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then item->>'end' else '00:00' end,
          coalesce(nullif(item->>'label',''),'Giải lao')
        from jsonb_array_elements(
          case when jsonb_typeof(source_session->'breaks')='array' then source_session->'breaks' else '[]'::jsonb end
        ) with ordinality as breaks(item,ordinality)
        where ordinality<=4
          and (nullif(btrim(item->>'after'),'') is null or item->>'after' ~ '^[1-8]$')
        on conflict (timetable_id,session,after_period) do nothing;

        insert into public.timetable_entries (timetable_id,session,day_id,period_id,subject)
        select root_timetable_id,session_name,grid.key,cells.ordinality::smallint,coalesce(cells.value #>> '{}','')
        from jsonb_each(
          case when jsonb_typeof(source_session->'grid')='object' then source_session->'grid' else '{}'::jsonb end
        ) as grid(key,value)
        cross join lateral jsonb_array_elements(
          case when jsonb_typeof(grid.value)='array' then grid.value else '[]'::jsonb end
        ) with ordinality as cells(value,ordinality)
        where grid.key in ('t2','t3','t4','t5','t6','t7') and cells.ordinality<=8
        on conflict (timetable_id,session,day_id,period_id) do nothing;
      end loop;

      source_notice := case when jsonb_typeof(source_value->'changeNotice')='object'
        then source_value->'changeNotice' else '{}'::jsonb end;
      insert into public.timetable_change_notices (
        timetable_id,active,has_changes,date_from,date_to,summary,lines,created_at
      ) values (
        root_timetable_id,
        coalesce(source_notice->>'active'='true',false),
        coalesce(source_notice->>'hasChanges'='true',false),
        case when pg_input_is_valid(coalesce(source_notice->>'from',source_notice->>'dateFrom'),'date')
          then coalesce(source_notice->>'from',source_notice->>'dateFrom')::date else null end,
        case when pg_input_is_valid(coalesce(source_notice->>'to',source_notice->>'dateTo'),'date')
          then coalesce(source_notice->>'to',source_notice->>'dateTo')::date else null end,
        coalesce(nullif(source_notice->>'summary',''),'Chưa có sự thay đổi'),
        case when jsonb_typeof(source_notice->'lines')='array' then source_notice->'lines' else '[]'::jsonb end,
        case when pg_input_is_valid(source_notice->>'createdAt','timestamptz')
          then (source_notice->>'createdAt')::timestamptz else now() end
      ) on conflict (timetable_id) do nothing;
    end if;
  end if;
end $$;

revoke all on public.timetables,public.timetable_sessions,public.timetable_periods,
  public.timetable_breaks,public.timetable_entries,public.timetable_change_notices from anon,authenticated;
grant all on public.timetables,public.timetable_sessions,public.timetable_periods,
  public.timetable_breaks,public.timetable_entries,public.timetable_change_notices to service_role;
notify pgrst, 'reload schema';
commit;
