-- Auth state migration. This file is intentionally NOT executed by the application.
-- Run after classroom_store-schema.sql (if classroom_store has not yet been created)
-- and before deploying the backend version that calls these RPCs.

create table if not exists public.ghost_account_sequence (
  sequence_key text primary key default 'global' check (sequence_key = 'global'),
  next_index bigint not null default 1 check (next_index >= 1),
  updated_at timestamptz not null default now()
);
insert into public.ghost_account_sequence(sequence_key, next_index)
values ('global', 1) on conflict (sequence_key) do nothing;

create table if not exists public.ghost_account_reservations (
  id uuid primary key,
  ghost_index bigint not null unique check (ghost_index >= 1),
  reserved_day date not null,
  reserved_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists ghost_account_reservations_day_idx
  on public.ghost_account_reservations(reserved_day);

create table if not exists public.ghost_account_creations (
  id bigint generated by default as identity primary key,
  ghost_index bigint not null unique check (ghost_index >= 1),
  user_id uuid unique references public.profiles(id) on delete set null,
  created_at timestamptz not null,
  created_day date not null,
  status text not null default 'created' check (status in ('created', 'released')),
  created_by_migration boolean not null default false
);
create index if not exists ghost_account_creations_day_idx
  on public.ghost_account_creations(created_day, status);

create table if not exists public.username_changes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  changed_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique(user_id, changed_at)
);
create index if not exists username_changes_user_changed_idx
  on public.username_changes(user_id, changed_at desc);

-- Keep source rows untouched. Migration is safe to re-run; conflicting identities
-- are ignored, and the sequence always advances beyond imported IDs.
do $$
declare
  source_value jsonb;
  item jsonb;
  at_ms numeric;
  max_index bigint := 0;
  raw_index bigint;
  raw_user_id uuid;
  raw_day date;
  user_key text;
  timestamp_value jsonb;
begin
  if to_regclass('public.classroom_store') is null then
    raise notice 'classroom_store absent: legacy backfill skipped; run this migration after the compatibility-store schema and rerun if needed';
  else
    execute 'select value from public.classroom_store where key = $1' into source_value using 'ghost-state';
    if jsonb_typeof(source_value) = 'object' then
      for item in select value from jsonb_array_elements(
        case when jsonb_typeof(source_value->'created')='array' then source_value->'created' else '[]'::jsonb end
      ) as x(value)
      loop
        begin
          raw_index := (item->>'index')::bigint;
          at_ms := (item->>'at')::numeric;
          raw_user_id := nullif(item->>'userId','')::uuid;
          if raw_index > 0 and at_ms > 0 then
            raw_day := (to_timestamp(at_ms / 1000) at time zone 'Asia/Ho_Chi_Minh')::date;
            insert into public.ghost_account_creations(ghost_index,user_id,created_at,created_day,status,created_by_migration)
            values(raw_index,raw_user_id,to_timestamp(at_ms / 1000),raw_day,'created',true)
            on conflict (ghost_index) do nothing;
            max_index := greatest(max_index, raw_index);
          end if;
        exception when others then
          raise notice 'Skipped malformed legacy ghost creation entry: %', item;
        end;
      end loop;

      for item in select value from jsonb_array_elements(
        case when jsonb_typeof(source_value->'reserved')='array' then source_value->'reserved' else '[]'::jsonb end
      ) as x(value)
      loop
        begin
          raw_index := (item->>'index')::bigint;
          at_ms := (item->>'at')::numeric;
          if raw_index > 0 and at_ms > 0 then
            raw_day := (to_timestamp(at_ms / 1000) at time zone 'Asia/Ho_Chi_Minh')::date;
            insert into public.ghost_account_reservations(id,ghost_index,reserved_day,reserved_at)
            values((item->>'id')::uuid,raw_index,raw_day,to_timestamp(at_ms / 1000))
            on conflict (id) do nothing;
            max_index := greatest(max_index, raw_index);
          end if;
        exception when others then
          raise notice 'Skipped malformed legacy ghost reservation entry: %', item;
        end;
      end loop;
      begin
        max_index := greatest(max_index, (source_value->>'nextIndex')::bigint - 1);
      exception when others then null;
      end;
    end if;

    execute 'select value from public.classroom_store where key = $1' into source_value using 'username-changes';
    if jsonb_typeof(source_value) = 'object' then
      for user_key in select key from jsonb_each(source_value)
      loop
        begin
          raw_user_id := user_key::uuid;
          for timestamp_value in select value from jsonb_array_elements(
            case when jsonb_typeof(source_value->user_key)='array' then source_value->user_key else '[]'::jsonb end
          ) as x(value)
          loop
            begin
              at_ms := (timestamp_value #>> '{}')::numeric;
              if at_ms > 0 then
                insert into public.username_changes(user_id, changed_at)
                values(raw_user_id, to_timestamp(at_ms / 1000))
                on conflict (user_id, changed_at) do nothing;
              end if;
            exception when others then
              raise notice 'Skipped malformed username-history timestamp for user %: %', user_key, timestamp_value;
            end;
          end loop;
        exception when others then
          raise notice 'Skipped malformed username-history user key: %', user_key;
        end;
      end loop;
    end if;
  end if;

  update public.ghost_account_sequence
  set next_index = greatest(next_index, max_index + 1), updated_at = now()
  where sequence_key = 'global';
end $$;

create or replace function public.ghost_preview_account()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_next bigint;
  v_remaining integer;
  v_today date := (now() at time zone 'Asia/Ho_Chi_Minh')::date;
begin
  select next_index into v_next from public.ghost_account_sequence where sequence_key = 'global';
  select greatest(0, 2 -
    (select count(*) from public.ghost_account_creations where created_day = v_today and status = 'created') -
    (select count(*) from public.ghost_account_reservations where reserved_day = v_today and reserved_at > now() - interval '30 minutes'))::integer
  into v_remaining;
  return jsonb_build_object('nextIndex', v_next, 'remainingToday', v_remaining,
    'limit', 2, 'email', case when v_remaining > 0 then 'taikhoanma-' || v_next || '@ghost.com' else null end);
end;
$$;

create or replace function public.ghost_reserve_account()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_next bigint;
  v_today date := (now() at time zone 'Asia/Ho_Chi_Minh')::date;
  v_id uuid := gen_random_uuid();
  v_used integer;
begin
  select next_index into v_next from public.ghost_account_sequence
    where sequence_key = 'global' for update;
  select (select count(*) from public.ghost_account_creations where created_day = v_today and status = 'created') +
         (select count(*) from public.ghost_account_reservations where reserved_day = v_today and reserved_at > now() - interval '30 minutes')
    into v_used;
  delete from public.ghost_account_reservations where reserved_at <= now() - interval '30 minutes';
  if v_used >= 2 then raise exception using errcode = 'P0001', message = 'GHOST_DAILY_LIMIT'; end if;
  update public.ghost_account_sequence set next_index = v_next + 1, updated_at = now()
    where sequence_key = 'global';
  insert into public.ghost_account_reservations(id,ghost_index,reserved_day)
    values(v_id,v_next,v_today);
  return jsonb_build_object('reservationId',v_id,'index',v_next);
end;
$$;

create or replace function public.ghost_finalize_account(p_reservation_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_reservation public.ghost_account_reservations%rowtype;
begin
  select * into v_reservation from public.ghost_account_reservations
    where id = p_reservation_id for update;
  if not found then
    if exists(select 1 from public.ghost_account_creations where user_id = p_user_id) then return; end if;
    raise exception using errcode = 'P0001', message = 'GHOST_RESERVATION_NOT_FOUND';
  end if;
  insert into public.ghost_account_creations(ghost_index,user_id,created_at,created_day,status)
    values(v_reservation.ghost_index,p_user_id,now(),v_reservation.reserved_day,'created');
  delete from public.ghost_account_reservations where id = p_reservation_id;
end;
$$;

create or replace function public.ghost_release_reservation(p_reservation_id uuid)
returns void
language sql
security definer
set search_path = public, pg_temp
as $$ delete from public.ghost_account_reservations where id = p_reservation_id $$;

create or replace function public.ghost_rollback_account(p_reservation_id uuid, p_user_id uuid default null)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_reservation public.ghost_account_reservations%rowtype;
begin
  select * into v_reservation from public.ghost_account_reservations
    where id = p_reservation_id for update;
  if found then
    insert into public.ghost_account_creations(ghost_index,user_id,created_at,created_day,status,created_by_migration)
    values(v_reservation.ghost_index,null,now(),v_reservation.reserved_day,'released',false)
    on conflict (ghost_index) do update set status = 'released', user_id = null;
    delete from public.ghost_account_reservations where id = p_reservation_id;
  elsif p_user_id is not null then
    update public.ghost_account_creations set status = 'released', user_id = null
      where user_id = p_user_id and status = 'created';
  end if;
end;
$$;

create or replace function public.change_display_name(
  p_user_id uuid, p_username text, p_record_change boolean default false
)
returns setof public.profiles
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile public.profiles%rowtype;
begin
  select * into v_profile from public.profiles where id = p_user_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'PROFILE_NOT_FOUND'; end if;
  if p_record_change then
    if (select count(*) from public.username_changes
        where user_id = p_user_id and changed_at > now() - interval '7 days') >= 2 then
      raise exception using errcode = 'P0001', message = 'USERNAME_WEEKLY_LIMIT';
    end if;
    insert into public.username_changes(user_id, changed_at) values(p_user_id, now());
  end if;
  update public.profiles set username = p_username, updated_at = now()
    where id = p_user_id returning * into v_profile;
  return next v_profile;
end;
$$;

alter table public.ghost_account_sequence enable row level security;
alter table public.ghost_account_reservations enable row level security;
alter table public.ghost_account_creations enable row level security;
alter table public.username_changes enable row level security;
revoke all on public.ghost_account_sequence, public.ghost_account_reservations,
  public.ghost_account_creations, public.username_changes from anon, authenticated;
grant all on public.ghost_account_sequence, public.ghost_account_reservations,
  public.ghost_account_creations, public.username_changes to service_role;
revoke all on function public.ghost_preview_account() from public, anon, authenticated;
revoke all on function public.ghost_reserve_account() from public, anon, authenticated;
revoke all on function public.ghost_finalize_account(uuid,uuid) from public, anon, authenticated;
revoke all on function public.ghost_release_reservation(uuid) from public, anon, authenticated;
revoke all on function public.ghost_rollback_account(uuid,uuid) from public, anon, authenticated;
revoke all on function public.change_display_name(uuid,text,boolean) from public, anon, authenticated;
grant execute on function public.ghost_preview_account() to service_role;
grant execute on function public.ghost_reserve_account() to service_role;
grant execute on function public.ghost_finalize_account(uuid,uuid) to service_role;
grant execute on function public.ghost_release_reservation(uuid) to service_role;
grant execute on function public.ghost_rollback_account(uuid,uuid) to service_role;
grant execute on function public.change_display_name(uuid,text,boolean) to service_role;
