-- Direct-to-Storage uploads for homework submissions. No binary data is stored in Postgres.
-- Run after supabase/supabase/homework-submission-schema.sql.

create table if not exists public.homework_upload_intents (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.homework_assignments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 minutes')
);
create index if not exists homework_upload_intents_user_exp_idx
  on public.homework_upload_intents(user_id, expires_at);

create table if not exists public.homework_upload_intent_files (
  id bigint generated by default as identity primary key,
  intent_id uuid not null references public.homework_upload_intents(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 20971520),
  created_at timestamptz not null default now()
);
create index if not exists homework_upload_intent_files_intent_idx
  on public.homework_upload_intent_files(intent_id);

alter table public.homework_upload_intents enable row level security;
alter table public.homework_upload_intent_files enable row level security;
revoke all on public.homework_upload_intents, public.homework_upload_intent_files from anon, authenticated;
grant all on public.homework_upload_intents, public.homework_upload_intent_files to service_role;

create or replace function public.homework_assignment_summary(p_assignment_ids uuid[], p_user_id uuid default null)
returns table(assignment_id uuid, submitted_count bigint, my_submitted_at timestamptz, my_file_count integer)
language sql
security definer
set search_path = public, pg_temp
as $$
  select a.id, count(s.id),
    max(s.submitted_at) filter (where s.user_id = p_user_id),
    coalesce(jsonb_array_length((array_agg(s.files order by s.submitted_at desc) filter (where s.user_id = p_user_id))[1]), 0)
  from public.homework_assignments a
  left join public.homework_submissions s on s.assignment_id = a.id
  where a.id = any(coalesce(p_assignment_ids, '{}'::uuid[]))
  group by a.id
$$;
revoke all on function public.homework_assignment_summary(uuid[],uuid) from public, anon, authenticated;
grant execute on function public.homework_assignment_summary(uuid[],uuid) to service_role;

create or replace function public.homework_commit_submission(
  p_intent_id uuid, p_user_id uuid, p_user_name text, p_today date
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_intent public.homework_upload_intents%rowtype;
  v_assignment public.homework_assignments%rowtype;
  v_old_files jsonb := '[]'::jsonb;
  v_files jsonb;
  v_submitted_at timestamptz := now();
begin
  select * into v_intent from public.homework_upload_intents
    where id = p_intent_id and user_id = p_user_id for update;
  if not found or v_intent.expires_at <= now() then
    raise exception using errcode = 'P0001', message = 'UPLOAD_INTENT_EXPIRED';
  end if;
  select * into v_assignment from public.homework_assignments
    where id = v_intent.assignment_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ASSIGNMENT_NOT_FOUND'; end if;
  if p_today < v_assignment.start_date or p_today > v_assignment.end_date then
    raise exception using errcode = 'P0001', message = 'ASSIGNMENT_CLOSED';
  end if;
  select files into v_old_files from public.homework_submissions
    where assignment_id = v_assignment.id and user_id = p_user_id for update;
  if found and not v_assignment.allow_resubmit then
    raise exception using errcode = 'P0001', message = 'RESUBMIT_NOT_ALLOWED';
  end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'path', storage_path, 'name', original_name, 'mime', mime_type, 'size', size_bytes
  ) order by id), '[]'::jsonb)
  into v_files from public.homework_upload_intent_files where intent_id = p_intent_id;
  if jsonb_array_length(v_files) < 1 or jsonb_array_length(v_files) > 10 then
    raise exception using errcode = 'P0001', message = 'INVALID_UPLOAD_MANIFEST';
  end if;
  insert into public.homework_submissions(assignment_id,user_id,user_name,files,submitted_at)
    values(v_assignment.id,p_user_id,nullif(p_user_name,''),v_files,v_submitted_at)
    on conflict (assignment_id,user_id) do update set
      user_name = excluded.user_name, files = excluded.files, submitted_at = excluded.submitted_at;
  delete from public.homework_upload_intents where id = p_intent_id;
  return jsonb_build_object('assignment_id',v_assignment.id,'submitted_at',v_submitted_at,
    'file_count',jsonb_array_length(v_files),'old_files',coalesce(v_old_files,'[]'::jsonb));
end;
$$;
revoke all on function public.homework_commit_submission(uuid,uuid,text,date) from public, anon, authenticated;
grant execute on function public.homework_commit_submission(uuid,uuid,text,date) to service_role;

notify pgrst, 'reload schema';
