export const ROUTES = Object.freeze({
  home: '/',
  login: '/dang-nhap',
  register: '/dang-ky',
  profile: '/thong-tin-ca-nhan',
  adminAccounts: '/quan-tri/tai-khoan',
  createRoom: '/tao-phong',
  createQuiz: '/tao-quiz',
  gameMode: '/tao-phong/game-mode',
  play: '/choi',
  room: '/phong',
  quizParty: '/quiz-party',
  boltSort: '/dai-chien-bu-long',
  pet: '/thu-cung',
})
